### ISSUE TITLE
feature: Add support for inputProps in `displayType="number"` component

### ISSUE THREAD

**Issue by ahmedsakri** [manojadams/mui-forms#40]
**Is your feature request related to a problem? Please describe.**
In displayType: "number", i want to pass `inputProps={{ step: 1000 }}` as Material UI (MUI) supports this out of the box and normal input element also supports it.

**Describe the solution you'd like**
Add a support for `inputProps={{ step: 1000 }}` in the component configuration.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by manojadams** [comment]
@ahmedsakri Added support for native html props in basic form controls.
**Sample example** 

```
{
    "fields": [{
        "name": "fieldInput1",
        "meta": {
            "displayName": "Field Input1",
            "displayType": "number",
            "htmlProps": {
                "step": 1000
            }
        }
    }]
}
```
