### ISSUE TITLE
Bug: Get Started Button Unresponsive on Landing Page (Mobile View)

### ISSUE THREAD

**Issue by dev-phantom** [manojadams/mui-forms#6]
**Issue Description:**
The "Get Started" button on the landing page is not clickable in the mobile view, preventing users from proceeding further into the application. Clicking the button does not trigger any action, rendering the user unable to access the app's main features.

**Steps to Reproduce:**
1. Open the application's landing page on a mobile device.
2. Attempt to click on the "Get Started" button.

**Expected Behavior:**
Clicking the "Get Started" button should lead users to the next step of the onboarding process or the main interface of the application.

**Actual Behavior:**
The "Get Started" button does not respond to clicks in the mobile view, and there is no visible indication that the button has been clicked.

**Additional Information:**
- This issue is specific to the mobile view.

**Screenshots/Attachments:**
![Screenshot_20230824-141724](https://github.com/manojadams/mui-forms/assets/72051159/4a4ab7f4-e6dd-462a-80e0-56ab27bbe725)

**Comment by manojadams** [comment]
@dev-phantom Thanks for noticing this and raising a bug.

**Comment by dev-phantom** [comment]
> @dev-phantom Thanks for noticing this and raising a bug.

I could fix this though

**Comment by manojadams** [comment]
@dev-phantom 
This is an open source project and just want to let you know that there are plans with this library to make it bigger.
So, you are welcome to add any changes (only if you want).

I would be fixing it though, eventually.

Thanks & Regards

**Comment by manojadams** [comment]
@dev-phantom A fix is deployed.
Let me know if you see this issue again.

**Comment by dev-phantom** [comment]
> @dev-phantom A fix is deployed. Let me know if you see this issue again.

This issue has been fixed 🚀
